datasets:
  # pretrain 3d visual grounding
  - json_path: data/GS-Reasoner-Data/3d_visual_grounding/scanrefer_train_llava_style.json
    sampling_strategy: "first:90%"
  - json_path: data/GS-Reasoner-Data/3d_visual_grounding/multi3drefer_train_llava_style.json
    sampling_strategy: "first:90%"
  - json_path: data/GS-Reasoner-Data/3d_visual_grounding/sr3d_train_llava_style.json
    sampling_strategy: "first:90%"
  - json_path: data/GS-Reasoner-Data/3d_visual_grounding/nr3d_train_llava_style.json
    sampling_strategy: "first:90%"
  - json_path: data/GS-Reasoner-Data/3d_visual_grounding/locate3d_scannet_train_llava_style.json
    sampling_strategy: "first:90%"